//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALUD_CDMX.wsSalud {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSalud.SaludSoap")]
    public interface SaludSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciaSesion", ReplyAction="*")]
        global::SALUD_CDMX.wsSalud.IniciaSesionResponse IniciaSesion(global::SALUD_CDMX.wsSalud.IniciaSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciaSesion", ReplyAction="*")]
        System.Threading.Tasks.Task<global::SALUD_CDMX.wsSalud.IniciaSesionResponse> IniciaSesionAsync(global::SALUD_CDMX.wsSalud.IniciaSesionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciaSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciaSesion", Namespace="http://tempuri.org/", Order=0)]
        public global::SALUD_CDMX.wsSalud.IniciaSesionRequestBody Body;
        
        public IniciaSesionRequest() {
        }
        
        public IniciaSesionRequest(global::SALUD_CDMX.wsSalud.IniciaSesionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IniciaSesionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public IniciaSesionRequestBody() {
        }
        
        public IniciaSesionRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciaSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciaSesionResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::SALUD_CDMX.wsSalud.IniciaSesionResponseBody Body;
        
        public IniciaSesionResponse() {
        }
        
        public IniciaSesionResponse(global::SALUD_CDMX.wsSalud.IniciaSesionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IniciaSesionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IniciaSesionResult;
        
        public IniciaSesionResponseBody() {
        }
        
        public IniciaSesionResponseBody(string IniciaSesionResult) {
            this.IniciaSesionResult = IniciaSesionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SaludSoapChannel : global::SALUD_CDMX.wsSalud.SaludSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaludSoapClient : System.ServiceModel.ClientBase<global::SALUD_CDMX.wsSalud.SaludSoap>, global::SALUD_CDMX.wsSalud.SaludSoap {
        
        public SaludSoapClient() {
        }
        
        public SaludSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaludSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaludSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaludSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::SALUD_CDMX.wsSalud.IniciaSesionResponse global::SALUD_CDMX.wsSalud.SaludSoap.IniciaSesion(global::SALUD_CDMX.wsSalud.IniciaSesionRequest request) {
            return base.Channel.IniciaSesion(request);
        }
        
        public string IniciaSesion(string user, string pass) {
            global::SALUD_CDMX.wsSalud.IniciaSesionRequest inValue = new global::SALUD_CDMX.wsSalud.IniciaSesionRequest();
            inValue.Body = new global::SALUD_CDMX.wsSalud.IniciaSesionRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            global::SALUD_CDMX.wsSalud.IniciaSesionResponse retVal = ((global::SALUD_CDMX.wsSalud.SaludSoap)(this)).IniciaSesion(inValue);
            return retVal.Body.IniciaSesionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::SALUD_CDMX.wsSalud.IniciaSesionResponse> global::SALUD_CDMX.wsSalud.SaludSoap.IniciaSesionAsync(global::SALUD_CDMX.wsSalud.IniciaSesionRequest request) {
            return base.Channel.IniciaSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::SALUD_CDMX.wsSalud.IniciaSesionResponse> IniciaSesionAsync(string user, string pass) {
            global::SALUD_CDMX.wsSalud.IniciaSesionRequest inValue = new global::SALUD_CDMX.wsSalud.IniciaSesionRequest();
            inValue.Body = new global::SALUD_CDMX.wsSalud.IniciaSesionRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((global::SALUD_CDMX.wsSalud.SaludSoap)(this)).IniciaSesionAsync(inValue);
        }
    }
}
